[package]
name = "gdfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
thiserror = "2.0.21"
tree-sitter = "0.27.0"
tree-sitter-gdscript = "6.1.0"

[dev-dependencies]
insta = "1.48.0"
mockall = "0.15.0"
rstest = "0.27.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"

[profile.ci]
inherits = "dev"
opt-level = 0
debug = "line-tables-only"
codegen-units = 4

[profile.ci.package."*"]
opt-level = 0
